FROM goreleaser/goreleaser-cross:v1.23.3@sha256:cc69304a8817dde675f0afe551c380545d5f34444946004961116ff394437a6f AS builder

RUN apt-get update
RUN apt-get install -y git

# TODO: pin it
RUN mkdir -p /Users/mpl
ENV GOPATH=/Users/mpl
RUN go install github.com/gokrazy/tools/cmd/gok@main

WORKDIR /Users/mpl/src/github.com/mpl/cgodemo/whisper
COPY ./whisper .
# TODO: just run make libwhisper.a in .cpp
RUN cd ./whisper.cpp/bindings/go && make whisper
ENV WHIPSPER_CPP=/Users/mpl/src/github.com/mpl/cgodemo/whisper/whisper.cpp

# TODO: move up when we've settled with this
WORKDIR /Users/mpl/src/github.com/mpl/cgodemo/gokrazy
COPY ./gokrazy .

# credentials for fetching private (repos) deps.
# N.B: gitcreds is going to leak into the docker image, so beware where we're building that.
ARG gitcreds
COPY ./gitcreds.sh .
RUN ./gitcreds.sh $gitcreds

# TODO: maybe remove
WORKDIR /Users/mpl/src/github.com/mpl/cgodemo/whisper
RUN make build

ENV GOPROXY=direct
ENV GOSUMDB=off
RUN make update
